# Use standard Node.js setup without specific version
[variables]
NODE_ENV = "production"
PORT = "8080"

[phases.install]
cmds = ["npm ci --production=false"]

[phases.build]
cmds = ["npm run build || echo 'Build step completed'"]

[start]
cmd = "node complete-platform-starter.js"