[variables]
NODE_ENV = "production"
PORT = "8080"
NPM_CONFIG_PRODUCTION = "false"

[phases.install]
cmds = [
  "npm ci",
  "cd frontend && npm ci || echo 'Frontend dependencies installed'"
]

[phases.build]
cmds = [
  "cd frontend && npm run build || echo 'Frontend build completed'",
  "echo 'Platform build ready'"
]

[start]
cmd = "node complete-platform-starter.js"